# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d178a3a600a5ec58fe2fe5af85ffc8ae"
name = "programmatic-creator"
handle = "programmatic-creator"
application_url = "https://passenger-relax-ra-beginner.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "os-test-sep.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://passenger-relax-ra-beginner.trycloudflare.com/auth/callback",
  "https://passenger-relax-ra-beginner.trycloudflare.com/auth/shopify/callback",
  "https://passenger-relax-ra-beginner.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
